### ISSUE TITLE
'Go to next exercise' button just reloading same question (answer and solution shown)

### ISSUE THREAD

**Issue by KateDavies** [Siyavula/monassis-issues#9]
When clicking on 'go to next exercise' button the site gets stuck. Rather than going to the next question it displays the same question, answered and with the worked solution. Clicking 'go to next exercise' again gets you:
'You already clicked the submit button. Do you really want to submit this form again?'

Forcing the resubmit eventually works (can take 3/4 tries).

Was practising template cd30c9fd but this has happened for at least 5 different templates so far.

Happens with the 'try another question like this' button as well.

![monassis_bug](https://cloud.githubusercontent.com/assets/3509110/5614900/4c08366a-94fe-11e4-852b-49b093da972d.png)

**Comment by njscheffler** [comment]
Just to add that Hannelie described very similar behaviour to me an hour or so ago.  I assumed from her description that she was simply seeing the same template, but now suspect the two things may be related.  I will chat to her tomorrow and see if we can replicate it.

**Comment by cscheffler** [comment]
This bug affects super users (template team members) only and the fix was made last year, but not deployed to live yet. Ever since we allowed linked concepts to be empty, the code had to be updated to handle this.

@KateDavies I updated the live code, so you should not experience this problem any more. Please reopen the issue if you do.

@nglenday This can not be the problem that Hannelie experienced since she is not a super user. If her problem persists, we will have to investigate that separately.
